# DSCI 503 - Homework 05
### Nathan Stratford

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
np.random.seed(1)
Z = np.random.uniform(0, 10, (5, 8))
Z = np.round(Z, 2)
print(Z)

[[4.17 7.2  0.   3.02 1.47 0.92 1.86 3.46]
 [3.97 5.39 4.19 6.85 2.04 8.78 0.27 6.7 ]
 [4.17 5.59 1.4  1.98 8.01 9.68 3.13 6.92]
 [8.76 8.95 0.85 0.39 1.7  8.78 0.98 4.21]
 [9.58 5.33 6.92 3.16 6.87 8.35 0.18 7.5 ]]


In [4]:
print(f"Row 3: {Z[2]}")
print(f"Column 6: {Z[2][5]}")

Row 3: [4.17 5.59 1.4  1.98 8.01 9.68 3.13 6.92]
Column 6: 9.68


In [5]:
row_sums = np.sum(Z, axis=1)
col_sums = np.sum(Z, axis=0)
array_sum = np.sum(Z)
print("Row Sums:")
print(row_sums)
print("Column Sums:", col_sums)
print("Array Sum:", array_sum)

Row Sums:
[22.1  38.19 40.88 34.62 47.89]
Column Sums: [30.65 32.46 13.36 15.4  20.09 36.51  6.42 28.79]
Array Sum: 183.68


## Problem 2: Reshaping and Stacking Arrays

In [7]:
np.random.seed(167)
x1 = np.random.normal(50, 10, 1000)  
x2 = np.random.normal(20, 5, 1000) 
x3 = np.random.normal(100, 30, 1000)
x4 = np.random.normal(10, 2, 1000)   
X = np.hstack([x1.reshape(-1, 1), x2.reshape(-1, 1), x3.reshape(-1, 1), x4.reshape(-1, 1)])
X = np.round(X, 2)
print(X.shape)

(1000, 4)
[[ 37.08  16.71 138.06   8.89]
 [ 41.32  19.91  99.61   9.86]
 [ 63.15  14.43  70.08  11.6 ]
 ...
 [ 36.96  16.05  81.28   9.9 ]
 [ 43.57  18.36 105.02  11.93]
 [ 65.06  21.47 136.37  11.84]]


In [8]:
print(X[:6])

[[ 37.08  16.71 138.06   8.89]
 [ 41.32  19.91  99.61   9.86]
 [ 63.15  14.43  70.08  11.6 ]
 [ 50.03  12.71  95.05   8.47]
 [ 55.05  24.4   62.16   9.49]
 [ 59.24  25.68  64.57  12.84]]


# Problem 3: Standardization

In [14]:
col_mean_array = np.mean(X, axis=0)
col_std_devs_array = np.std(X, axis=0)
print("Column means:")
print(np.round(col_mean_array, 2))
print("Column standard deviations:")
print(np.round(col_std_devs_array, 2))

Column means:
[50.21 19.86 99.84 10.06]
Column standard deviations:
[ 9.69  5.08 30.88  2.03]


In [16]:
W = (X - col_mean_array) / col_std_devs_array
W_col_mean = np.mean(W, axis=0)
W_col_std_dev = np.std(W, axis=0)
print("Column means:")
print(np.round(W_col_mean, 2))
print("Column standard deviations:")
print(np.round(W_col_std_dev, 2))

Column means:
[ 0. -0. -0. -0.]
Column standard deviations:
[1. 1. 1. 1.]


In [ ]:
auto = pd.DataFrame()